apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skills-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: skills
        tier: frontend
    spec:
      containers:
      - name: skills-web
        image: registry.hub.docker.com/senforsce/skills-web:latest
        imagePullPolicy: Always
        env:
        - name: APP_HOST
          value: 0.0.0.0
        - name: GRAPHQL_HOST
          value: skills-api
        - name: GRAPHQL_PORT
          value: "3000"
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        ports:
        - containerPort: 5000
