#!/bin/bash

set -e -u

if [ -z ${1+x} ]; then
  echo "Missing argument 1: storybook port"
  exit 1
elif [ -z ${2+x} ]; then
  echo "Missing argument 2: screenshots_dir"
  exit 1
fi

storybook_port="$1"
screenshots_destination="$2"

rm -Rf ${screenshots_destination}/*
storybook-chrome-screenshot -p "${storybook_port}" -c ".storybook" -o "${screenshots_destination}"
