jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: version
  - get: repo
    trigger: true
  - put: skills-web-image
    params:
      build: repo
      tag: version/number
      cache_tag: latest
      cache: true
  - put: version
    params: {bump: minor}
- name: stage
  public: true
  serial: true
  plan:
  - get: repo
    passed: [build]
  - get: version
    passed: [build]
    trigger: true
  - get: skills-web-image
    passed: [build]
    trigger: true
  - put: staging
    params:
      image_name: repo/ci/DOCKER_IMAGE_NAME
      image_tag: version/number
- name: ship
  public: true
  serial: true
  plan:
  - get: repo
    passed: [stage]
  - get: version
    passed: [stage]
  - get: staging
    passed: [stage]
  - put: prod
    params:
      image_name: repo/ci/DOCKER_IMAGE_NAME
      image_tag: version/number

resources:
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: git@gitlab.com:ornous/skills/web.git
    branch: version
    file: version
    private_key: {{gitlab-private-key}}

- name: repo
  type: git
  source:
    uri: git@gitlab.com:ornous/skills/web.git
    branch: master
    private_key: {{gitlab-private-key}}

- name: skills-web-image
  type: docker-image
  source:
    repository: senforsce/skills-web
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: staging
  type: kubernetes
  source:
    namespace: staging
    resource_type: deployment
    resource_name: skills-web
    container_name: skills-web
    cluster_url: {{kubernetes-cluster-url}}
    cluster_ca: {{kubernetes-cluster-ca}}
    admin_key: {{kubernetes-admin-key}}
    admin_cert: {{kubernetes-admin-cert}}

- name: prod
  type: kubernetes
  source:
    namespace: production
    resource_type: deployment
    resource_name: skills-web
    container_name: skills-web
    cluster_url: {{kubernetes-cluster-url}}
    cluster_ca: {{kubernetes-cluster-ca}}
    admin_key: {{kubernetes-cluster-ca}}
    admin_cert: {{kubernetes-cluster-ca}}

resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: jcderr/concourse-kubernetes-resource
